/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_kastle_webrtc_PeerConnectionFactory */

#ifndef _Included_dev_kastle_webrtc_PeerConnectionFactory
#define _Included_dev_kastle_webrtc_PeerConnectionFactory
#ifdef __cplusplus
extern "C" {
#endif

	/*
	 * Class:     dev_kastle_webrtc_PeerConnectionFactory
	 * Method:    createPeerConnection
	 * Signature: (Ldev/kastle/webrtc/RTCConfiguration;Ldev/kastle/webrtc/PeerConnectionObserver;)Ldev/kastle/webrtc/RTCPeerConnection;
	 */
	JNIEXPORT jobject JNICALL Java_dev_kastle_webrtc_PeerConnectionFactory_createPeerConnection
	(JNIEnv *, jobject, jobject, jobject);

	/*
	 * Class:     dev_kastle_webrtc_PeerConnectionFactory
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_kastle_webrtc_PeerConnectionFactory_dispose
	(JNIEnv *, jobject);

    /*
    * Class:     dev_kastle_webrtc_PeerConnectionFactory
    * Method:    initialize
    * Signature: ()V
    */
    JNIEXPORT void JNICALL Java_dev_kastle_webrtc_PeerConnectionFactory_initialize
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
