/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_PeerConnectionFactory */

#ifndef _Included_dev_onvoid_webrtc_PeerConnectionFactory
#define _Included_dev_onvoid_webrtc_PeerConnectionFactory
#ifdef __cplusplus
extern "C" {
#endif

	/*
	 * Class:     dev_onvoid_webrtc_PeerConnectionFactory
	 * Method:    createPeerConnection
	 * Signature: (Ldev/onvoid/webrtc/RTCConfiguration;Ldev/onvoid/webrtc/PeerConnectionObserver;)Ldev/onvoid/webrtc/RTCPeerConnection;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_PeerConnectionFactory_createPeerConnection
	(JNIEnv *, jobject, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_PeerConnectionFactory
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_PeerConnectionFactory_dispose
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_PeerConnectionFactory
	 * Method:    initialize
	 * Signature: (Ldev/onvoid/webrtc/media/audio/AudioDeviceModule;Ldev/onvoid/webrtc/media/audio/AudioProcessing;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_PeerConnectionFactory_initialize
	(JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
